### ISSUE TITLE
Erro SimpleClans v2.7.13-SNAPSHOT

### ISSUE THREAD

**Issue by SrBedrock** [RoboMWM/SimpleClans#8]
```
[23:29:59 WARN]: [SimpleClans] Plugin SimpleClans v2.7.13-SNAPSHOT generated an exception while executing task 54
java.lang.IllegalStateException: RequestEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.3.jar:git-Paper-132]
        at net.sacredlabyrinth.phaed.simpleclans.managers.RequestManager.ask(RequestManager.java:468) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.RequestManager$1.run(RequestManager.java:427) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.3.jar:git-Paper-132]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.3.jar:git-Paper-132]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Server version: Paper-132 (1.14.3)
 SimpleClans: v2.7.13-SNAPSHOT

**Comment by RoboMWM** [comment]
~~Dang I guess people are using my fork.~~ You aren't using my fork. Report the error on the parent repo.

Looks like a custom event, so the event has to mark itself as asynchronous.
